// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "xmodel/head_us_ranger_braeburn";
	a[1] = "xmodel/head_us_ranger_david";
	a[2] = "xmodel/head_us_ranger_frank";
	a[3] = "xmodel/head_us_ranger_grant";
	a[4] = "xmodel/head_us_ranger_harry";
	a[5] = "xmodel/head_us_ranger_medic_wells";
	a[6] = "xmodel/head_us_ranger_mo";
	a[7] = "xmodel/head_us_ranger_preston";
	a[8] = "xmodel/head_us_ranger_randall";
	a[9] = "xmodel/head_us_ranger_wolf";
	return a;
}