// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/sas_pluxy_hunter");
	self setViewmodel("xmodel/viewmodel_hands_cloth");
}

precache()
{
	precacheModel("xmodel/sas_pluxy_hunter");
	precacheModel("xmodel/viewmodel_hands_cloth");
}
