// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/zombie_pluxy_infected");
	self setViewmodel("xmodel/viewmodel_hands_german");
}

precache()
{
	precacheModel("xmodel/zombie_pluxy_infected");
	precacheModel("xmodel/viewmodel_hands_german");
}
