// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\mp_body_british_africa::main());
	self setViewmodel("xmodel/viewmodel_hands_british_bare");
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\mp_body_british_africa::main());
	precacheModel("xmodel/viewmodel_hands_british_bare");
}
