// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\mp_body_russian_coat::main());
	self setViewmodel("xmodel/viewmodel_hands_russian");
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\mp_body_russian_coat::main());
	precacheModel("xmodel/viewmodel_hands_russian");
}
