// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	//codescripts\character::setModelFromArray(xmodelalias\mp_body_zombie::main());
	self setModel("xmodel/zombie_pluxy_infected");
	self setViewmodel("xmodel/viewmodel_hands_cloth");
}

precache()
{
	//codescripts\character::precacheModelArray(xmodelalias\mp_body_zombie::main());
	precacheModel("xmodel/zombie_pluxy_infected");
	precacheModel("xmodel/viewmodel_hands_cloth");
}
